In [2]:
import pandas as pd
import numpy as np

In [3]:
df=pd.DataFrame([[1,2,3,4],[1,2,3,4],[2,1,3,4],[4,2,3,1],[1,2,3,4]],columns=["A","B","C","D"])
df

   A  B  C  D
0  1  2  3  4
1  1  2  3  4
2  2  1  3  4
3  4  2  3  1
4  1  2  3  4

In [6]:
df.duplicated()

0    False
1     True
2    False
3    False
4     True
dtype: bool

In [7]:
df.duplicated().sum()

2

In [8]:
df.duplicated(subset=["B"]).sum()

3

In [9]:
df.duplicated(subset=["B","D"]).sum()

2

In [10]:
df.drop_duplicates()

   A  B  C  D
0  1  2  3  4
2  2  1  3  4
3  4  2  3  1

In [11]:
df

   A  B  C  D
0  1  2  3  4
1  1  2  3  4
2  2  1  3  4
3  4  2  3  1
4  1  2  3  4

In [12]:
df.drop_duplicates(keep="last")

   A  B  C  D
2  2  1  3  4
3  4  2  3  1
4  1  2  3  4

In [16]:
df.drop_duplicates(keep=False) #all duplicate is remove

   A  B  C  D
2  2  1  3  4
3  4  2  3  1

In [22]:
df

   A  B  C  D
0  1  2  3  4
1  1  2  3  4
2  2  1  3  4
3  4  2  3  1
4  1  2  3  4

In [19]:
df.drop_duplicates(subset=["B"])

   A  B  C  D
0  1  2  3  4
2  2  1  3  4

In [24]:
df.drop_duplicates(subset=["B"],keep="last")

   A  B  C  D
2  2  1  3  4
4  1  2  3  4